[deps]
AbstractAlgebra = "c3fe647b-3220-5bb0-a1ea-a7954cac585d"
LinearAlgebraX = "9b3f67b0-2d00-526e-9884-9e4938f8fb88"
Mods = "7475f97c-0381-53b1-977b-4c60186c8d62"
Modulo2 = "7e4462cd-8001-4c22-b109-db8e4e581e9c"
Nemo = "2edaba10-b0f1-5616-af89-8c11ac63239a"
